FROM microsoft/dotnet:2.2-sdk
WORKDIR /app

COPY Noname15/*.sln .
COPY Noname15/CleanCityCore/*.csproj ./CleanCityCore/CleanCityCore.csproj
COPY Noname15/BackendApi/*.csproj ./BackendApi/BackendApi.csproj
COPY Noname15/CleanCityTests/*.csproj ./CleanCityTests/CleanCityTests.csproj
COPY Noname15/EmailSenderDaemon/*.csproj ./EmailSenderDaemon/EmailSenderDaemon.csproj
RUN dotnet restore

COPY Noname15/CleanCityCore/. ./CleanCityCore
WORKDIR /app/CleanCityCore
RUN dotnet publish -c Release -o out

WORKDIR /app

COPY entrypoint.db.sh .
CMD /bin/bash ./entrypoint.db.sh
